Meta-Llama-3-8B-Instruct: "/fs-computility/llm/shared/llm_llama3_hf/Meta-Llama-3-8B-Instruct/"
Meta-Llama-3.1-8B-Instruct: "/fs-computility/llm/shared/llm_llama3_hf/Llama3.1-8B-Instruct/"
Meta-Llama-3.1-70B-Instruct: "/fs-computility/llm/shared/llm_llama3_hf/Llama3.1-70B-Instruct/"
Meta-Llama-3.1-405B-Instruct: "/fs-computility/llm/shared/llm_llama3_hf/Meta-Llama-3.1-405B-Instruct/"
Qwen2.5-72B-Instruct: "/fs-computility/llm/shared/llm_qwen/Qwen2.5-72B-Instruct/"
Qwen2.5-14B-Instruct: "/fs-computility/llm/shared/llm_qwen/Qwen2.5-14B-Instruct/"
Qwen2.5-7B-Instruct: "/fs-computility/llm/shared/llm_qwen/Qwen2.5-7B-Instruct/"